# Filter

In [12]:
import scipy.stats as sp
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import cv2
from PIL import ImageFont, ImageDraw, Image

In [2]:
img = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype="uint8")

kernel = np.array([[0,0,0],
                  [0,1,0],
                  [0,0,0]])     # 원본이미지가 그대로 나온다.
filtered = cv2.filter2D(img, -1, kernel)
print(filtered) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
img = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype="uint8")

kernel = np.array([[1,0,0],    # 1자리에 있는 픽셀만 계산하겠다!
                  [0,0,0],
                  [0,0,0]])     
filtered = cv2.filter2D(img, -1, kernel)
print(filtered) 

# 9개 픽셀을 계산했을때, 
'''
5   4   5  ㅁ ㅁ
   ㅡ ㅡ ㅡ ㅡ
2 |*1*  2  3 |ㅁ 
5 | 4   5  6 |ㅁ
ㅁ| 7   8  9 |ㅁ
   ㅡ ㅡ ㅡ ㅡ
 ㅁ ㅁ ㅁ ㅁ ㅁ
'''
# 계산하고자 하는 기준픽셀의 대각선 자리에 있는 값을 가져온다.
# 거울을 놓은 것 처럼 reflection 된 것!

[[5 4 5]
 [2 1 2]
 [5 4 5]]


In [4]:
img = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype="uint8")

kernel = np.array([[0,1,0],
                  [0,0,0],
                  [0,0,0]])     
filtered = cv2.filter2D(img, -1, kernel)
print(filtered) 

[[4 5 6]
 [1 2 3]
 [4 5 6]]


In [5]:
img = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype="uint8")

kernel = np.array([[0,0,0],
                  [1,0,1],    # 좌우값을 더한 값이 나타남. 
                  [0,0,0]])     
filtered = cv2.filter2D(img, -1, kernel)
print(filtered) 

[[ 4  4  4]
 [10 10 10]
 [16 16 16]]


## 패딩 정규화

In [8]:
img = np.array([
      [1,2,3],
    [200,5,200],
    [7,8,9]
], dtype="float")

kernel = np.array([[0,0,0],
                   [1,0,-1],
                   [0,0,0]
                  ])
filtered = cv2.filter2D(img, -1, kernel)
print(filtered)

[[ 0. -2.  0.]
 [ 0.  0.  0.]
 [ 0. -2.  0.]]


In [9]:
cv2.imwrite("output.png", filtered.astype('uint8'))

img = cv2.imread("output.png")
print(img)

[[[  0   0   0]
  [254 254 254]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [254 254 254]
  [  0   0   0]]]


In [17]:
ma = np.max(filtered)
mm = np.min(filtered)

n = (filtered - mm) / (ma - mm) * 255   # -2~0 -> 0~255
print(n)
# 수동으로 minmax값 계산해서 정규화

n2 = np.abs(filtered) / np.max(np.abs(filtered))* 255   # 0~2 -> 0~255
print(n2)

norm = cv2.normalize(filtered, None, 0 , 255, cv2.NORM_MINMAX)
norm = norm.astype('uint8')
print(norm)
# 자동으로 함수 이용해서 정규화
# 정규화하는 이유는, 눈으로 영상을 보기위해서. 계산하기위해서가 아님.

[[255.   0. 255.]
 [255. 255. 255.]
 [255.   0. 255.]]
[[  0. 255.   0.]
 [  0.   0.   0.]
 [  0. 255.   0.]]
[[255   0 255]
 [255 255 255]
 [255   0 255]]


In [26]:
src = cv2.imread('lena.png', cv2.IMREAD_GRAYSCALE)
src2 = src.astype('int16')

kernel = np.array([[0,1,0],
                   [0,0,0],
                   [0,-1,0]
                  ])

filtered = cv2.filter2D(src2, -1, kernel)
print(np.min(filtered))
print(np.max(filtered))
cv2.imwrite("output.png", filtered)


filtered2 = cv2.filter2D(src2, -1, kernel) + 128
cv2.imwrite("output2.png", filtered2)


filtered3 = cv2.normalize(filtered, None, 0, 255, cv2.NORM_MINMAX)
print(np.min(filtered3))
print(np.max(filtered3))                         
cv2.imwrite("output3.png", filtered3)


#plt.imshow(cv2.cvtColor(filtered, cv2.COLOR_BGR2RGB))

-190
170
0
255


True

In [27]:
src = cv2.imread('shape.png', cv2.IMREAD_GRAYSCALE)
src2 = src.astype('int16')

kernel = np.array([[0,1,0],
                   [0,0,0],
                   [0,-1,0]
                  ])
filtered = cv2.filter2D(src2, -1, kernel)
cv2.imwrite("output.png", filtered)

# 수평 edge만 나오고 수직 edge는 검출이 안됨.

True

In [28]:
src = cv2.imread('shape.png', cv2.IMREAD_GRAYSCALE)
src2 = src.astype('int16')

kernel = np.array([[0,0,0],
                   [1,0,-1],
                   [0,0,0]
                  ])
filtered = cv2.filter2D(src2, -1, kernel)
cv2.imwrite("output.png", filtered)

# 수직 edge만 나오고 수평 edge는 검출이 안됨.
# 수평, 수직 모두 검출하고싶다면 둘을 더해줘야한다.

True

In [29]:
src = cv2.imread('shape2.png', cv2.IMREAD_GRAYSCALE)
src2 = src.astype('int16')

kernel = np.array([[0,0,0],
                   [1,0,-1],
                   [0,0,0]
                  ])
filtered = cv2.filter2D(src2, -1, kernel)
cv2.imwrite("output_shape.png", filtered)

True

> ### 영역처리를 통한 edge 검출 활용 

<br> 다양한 형태의 미분(좌우를 뺀다거나 대각선을 뺀다던가 하는 등 필터)을 통해서

- 반도체 불량 검사
- 자율주행차 차선, 자율주행 빗물 반사
- 동전 인식
- 바둑판 인식 등등